name: Performance Monitoring

on:
  schedule:
    # Run performance checks daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
  
jobs:
  performance-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Run bundle analysis
        run: npm run build:analyze
        
      - name: Check bundle size limits
        run: npm run build:size
        
      - name: Run Lighthouse CI
        run: npm run performance:audit
        
      - name: Upload performance results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: performance-results-${{ github.run_number }}
          path: |
            .lighthouseci/
            dist/
          retention-days: 90
          if-no-files-found: warn
          
      - name: Comment PR with performance results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Read Lighthouse results and create comment
            const resultsPath = '.lighthouseci/';
            if (fs.existsSync(resultsPath)) {
              const comment = `## Performance Audit Results
              
              ✅ Performance audit completed for commit \`${context.sha.substring(0, 7)}\`
              
              See attached artifacts for detailed results.`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }